@startuml

title __BOWLING-ALLEY's Class Diagram__\n

  namespace  {
    class drive {
    }
  }
  

  namespace  {
    namespace vents {
      class events.ControlDeskEvent {
      }
    }
  }
  

  namespace  {
    namespace vents {
      class events.LaneEvent {
      }
    }
  }
  

  namespace  {
    namespace vents {
      class events.PinsetterEvent {
      }
    }
  }
  

  namespace  {
    namespace anagers {
      class managers.ControlDeskManager {
      }
    }
  }
  

  namespace  {
    namespace anagers {
      class managers.LaneManager {
      }
    }
  }
  

  namespace  {
    namespace anagers {
      class managers.PinsetterManager {
      }
    }
  }
  

  namespace  {
    namespace odels {
      class models.Bowler {
      }
    }
  }
  

  namespace  {
    namespace odels {
      class models.ControlDesk {
      }
    }
  }
  

  namespace  {
    namespace odels {
      class models.Lane {
      }
    }
  }
  

  namespace  {
    namespace odels {
      class models.Party {
      }
    }
  }
  

  namespace  {
    namespace odels {
      class models.Pinsetter {
      }
    }
  }
  

  namespace  {
    namespace odels {
      class models.Score {
      }
    }
  }
  

  namespace  {
    namespace odels {
      class models.ScoreBoard {
      }
    }
  }
  

  namespace  {
    namespace odels {
      class models.ScoreReport {
      }
    }
  }
  

  namespace  {
    namespace bservers {
      interface observers.ControlDeskObserver {
      }
    }
  }
  

  namespace  {
    namespace bservers {
      interface observers.LaneObserver {
      }
    }
  }
  

  namespace  {
    namespace bservers {
      interface observers.PinsetterObserver {
      }
    }
  }
  

  namespace  {
    namespace tils {
      class utils.BowlerFile {
      }
    }
  }
  

  namespace  {
    namespace tils {
      class utils.PrintableText {
      }
    }
  }
  

  namespace  {
    namespace tils {
      class utils.Queue {
      }
    }
  }
  

  namespace  {
    namespace tils {
      class utils.ScoreHistoryFile {
      }
    }
  }
  

  namespace  {
    namespace tils {
      class utils.UiComponents {
      }
    }
  }
  

  namespace  {
    namespace iews {
      class views.AddPartyView {
      }
    }
  }
  

  namespace  {
    namespace iews {
      class views.ControlDeskView {
      }
    }
  }
  

  namespace  {
    namespace iews {
      class views.EndGamePromptView {
      }
    }
  }
  

  namespace  {
    namespace iews {
      class views.EndGameReportView {
      }
    }
  }
  

  namespace  {
    namespace iews {
      class views.LaneStatusView {
      }
    }
  }
  

  namespace  {
    namespace iews {
      class views.LaneView {
      }
    }
  }
  

  namespace  {
    namespace iews {
      class views.LaneViewHelper {
      }
    }
  }
  

  namespace  {
    namespace iews {
      class views.NewPatronView {
      }
    }
  }
  

  namespace  {
    namespace iews {
      class views.PinSetterView {
      }
    }
  }
  

  models.Lane .up.|> PinsetterObserver
  utils.PrintableText .up.|> Printable
  views.AddPartyView .up.|> ActionListener
  views.AddPartyView .up.|> ListSelectionListener
  views.ControlDeskView .up.|> ActionListener
  views.ControlDeskView .up.|> ControlDeskObserver
  views.EndGamePromptView .up.|> ActionListener
  views.EndGameReportView .up.|> ActionListener
  views.EndGameReportView .up.|> ListSelectionListener
  views.LaneStatusView .up.|> ActionListener
  views.LaneStatusView .up.|> LaneObserver
  views.LaneStatusView .up.|> PinsetterObserver
  views.LaneView .up.|> ActionListener
  views.LaneView .up.|> LaneObserver
  views.NewPatronView .up.|> ActionListener
  views.PinSetterView .up.|> PinsetterObserver


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
