@startuml

title __OLD-CODE's Class Diagram__\n

  namespace  {
    class AddPartyView {
    }
  }
  

  namespace  {
    class Alley {
    }
  }
  

  namespace  {
    class Bowler {
    }
  }
  

  namespace  {
    class BowlerFile {
    }
  }
  

  namespace  {
    class ControlDesk {
    }
  }
  

  namespace  {
    class ControlDeskEvent {
    }
  }
  

  namespace  {
    interface ControlDeskObserver {
    }
  }
  

  namespace  {
    class ControlDeskView {
    }
  }
  

  namespace  {
    class EndGamePrompt {
    }
  }
  

  namespace  {
    class EndGameReport {
    }
  }
  

  namespace  {
    class Lane {
    }
  }
  

  namespace  {
    class LaneEvent {
    }
  }
  

  namespace  {
    interface LaneEventInterface {
    }
  }
  

  namespace  {
    interface LaneObserver {
    }
  }
  

  namespace  {
    interface LaneServer {
    }
  }
  

  namespace  {
    class LaneStatusView {
    }
  }
  

  namespace  {
    class LaneView {
    }
  }
  

  namespace  {
    class NewPatronView {
    }
  }
  

  namespace  {
    class Party {
    }
  }
  

  namespace  {
    class PinSetterView {
    }
  }
  

  namespace  {
    class Pinsetter {
    }
  }
  

  namespace  {
    class PinsetterEvent {
    }
  }
  

  namespace  {
    interface PinsetterObserver {
    }
  }
  

  namespace  {
    class PrintableText {
    }
  }
  

  namespace  {
    class Queue {
    }
  }
  

  namespace  {
    class Score {
    }
  }
  

  namespace  {
    class ScoreHistoryFile {
    }
  }
  

  namespace  {
    class ScoreReport {
    }
  }
  

  namespace  {
    class drive {
    }
  }
  

  AddPartyView .up.|> java.awt.event.ActionListener
  AddPartyView .up.|> javax.swing.event.ListSelectionListener
  AddPartyView o-- ControlDeskView : controlDesk
  Alley o-- ControlDesk : controldesk
  ControlDesk o-- Queue : partyQueue
  ControlDeskView .up.|> ControlDeskObserver
  ControlDeskView .up.|> java.awt.event.ActionListener
  ControlDeskView o-- ControlDesk : controlDesk
  EndGamePrompt .up.|> java.awt.event.ActionListener
  EndGameReport .up.|> java.awt.event.ActionListener
  EndGameReport .up.|> javax.swing.event.ListSelectionListener
  Lane .up.|> PinsetterObserver
  Lane o-- Bowler : currentThrower
  Lane o-- Party : party
  Lane o-- Pinsetter : setter
  LaneEvent o-- Bowler : bowler
  LaneEvent o-- Party : p
  LaneStatusView .up.|> LaneObserver
  LaneStatusView .up.|> PinsetterObserver
  LaneStatusView .up.|> java.awt.event.ActionListener
  LaneStatusView o-- Lane : lane
  LaneStatusView o-- LaneView : lv
  LaneStatusView o-- PinSetterView : psv
  LaneView .up.|> LaneObserver
  LaneView .up.|> java.awt.event.ActionListener
  LaneView o-- Lane : lane
  NewPatronView .up.|> java.awt.event.ActionListener
  NewPatronView o-- AddPartyView : addParty
  PinSetterView .up.|> PinsetterObserver
  PrintableText .up.|> java.awt.print.Printable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
