/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import dbAccess.ConfigCache;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author sbose
 */
public class ConfigMenuView extends javax.swing.JFrame {

    /**
     * Creates new form ConfigMenu
     */
    public ConfigMenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lanes = new javax.swing.JLabel();
        numberOfLanes = new javax.swing.JTextField();
        lanes1 = new javax.swing.JLabel();
        patrons = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

        lanes.setText("Maximum number of Lanes");
        numberOfLanes.setText(ConfigCache.getConfig("NUMBER_OF_LANES"));
        patrons.setText(ConfigCache.getConfig("MAX_PATRONS_PER_PARTY"));

        lanes1.setText("Maximum number of Patrons");


        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lanes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lanes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patrons)
                    .addComponent(numberOfLanes)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lanes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numberOfLanes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lanes1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(patrons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(saveButton)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
        Dimension screenSize = (Toolkit.getDefaultToolkit()).getScreenSize();
        setLocation(
                ((screenSize.width) / 2) - ((getSize().width) / 2),
                ((screenSize.height) / 2) - ((getSize().height) / 2));
        setVisible(true);
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String maxPatrons=patrons.getText();
        String numLanes=numberOfLanes.getText();
        if(maxPatrons.isEmpty() || numLanes.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Configurations cannot be empty","Alert",JOptionPane.WARNING_MESSAGE);
            return;
        }
        ConfigCache.putConfig("MAX_PATRONS_PER_PARTY",maxPatrons);
        ConfigCache.putConfig("NUMBER_OF_LANES",numLanes);
        JOptionPane.showMessageDialog(this,"Configurations updated,restart system to take effect");
    }
    private javax.swing.JLabel lanes;
    private javax.swing.JLabel lanes1;
    private javax.swing.JTextField numberOfLanes;
    private javax.swing.JTextField patrons;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
