/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import dbAccess.AdhocQuery;
import dbAccess.QueryBuilder;
import models.Query;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.util.List;

/**
 *
 * @author sbose
 */
public class QueryCreatorView extends javax.swing.JFrame {
    DefaultListModel<String> listModal;
    /**
     * Creates new form NewJFrame
     */
    AdhocQueryView adhocQueryviewRef;
    public QueryCreatorView(AdhocQueryView view) {
        adhocQueryviewRef=view;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        String[] tables=AdhocQuery.fetchTables();
        String[] initCols=AdhocQuery.fetchColumnsByTableName(tables[0]);
        listModal = new DefaultListModel<String>();
        initToModal(listModal,initCols);
        jPanel1 = new javax.swing.JPanel();
        sqlNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        tableSelector = new javax.swing.JComboBox<String>(tables);
        tableLAbel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        columnsSelector = new javax.swing.JList<String>(listModal);
        jLabel2 = new javax.swing.JLabel();
        where = new javax.swing.JLabel();
        valueSelector = new javax.swing.JTextField();
        whereSelector = new javax.swing.JComboBox<String>(initCols);
        where1 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        queryButton = new javax.swing.JButton();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Query Builder");

        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("SQL Name");
        tableSelector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tableSelectorItemStateChanged(evt);
            }
        });

        tableLAbel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableLAbel.setText("Select Table");
        jScrollPane1.setViewportView(columnsSelector);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select Columns");

        where.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        where.setText("Where");

        where1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        where1.setText("Equals");

        saveButton.setText("Save");
        saveButton.setActionCommand("");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        queryButton.setText("Query");
        queryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryButtonActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(queryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sqlNameTextField)
                                .addComponent(tableSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tableLAbel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(where, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                .addComponent(valueSelector)
                                .addComponent(whereSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(where1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sqlNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tableLAbel)
                .addGap(18, 18, 18)
                .addComponent(tableSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(where)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(whereSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(where1)
                .addGap(18, 18, 18)
                .addComponent(valueSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(queryButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        Dimension screenSize = (Toolkit.getDefaultToolkit()).getScreenSize();
        setLocation(
                ((screenSize.width) / 2) - ((getSize().width) / 2),
                ((screenSize.height) / 2) - ((getSize().height) / 2));
        setVisible(true);
    }
    private String buildSqlScript()
    {
        String tableName=(String) tableSelector.getSelectedItem();
        List<String> cols=columnsSelector.getSelectedValuesList();
        StringBuilder sqlScript=new StringBuilder();
        sqlScript.append(QueryBuilder.selectClause(tableName,cols));
        String cond=(String)whereSelector.getSelectedItem();
        sqlScript.append(QueryBuilder.whereClause(cond));
        return sqlScript.toString();
    }
    private void queryButtonActionPerformed(ActionEvent evt) {
        String sql=buildSqlScript();
        String value=valueSelector.getText();
        Object[] cols = AdhocQuery.fetchColumnsByScript(sql,value);
        Object[][] data = AdhocQuery.executeAdHocScriptbySql(sql,value);
        QueryResultView queryResultView = new QueryResultView(cols, data);
    }

    private void saveButtonActionPerformed(ActionEvent evt) {
        String sql=buildSqlScript();
        String value=valueSelector.getText();
//        sql.replace("?","\""+value+"\"");
        String sqlName=sqlNameTextField.getText();
        if(sqlName.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Sql name cannot be empty","Alert",JOptionPane.WARNING_MESSAGE);
            return;
        }
        String message=JOptionPane.showInputDialog(this,"Enter message");
        AdhocQuery.insertScript(new Query(0,sqlName,sql,"INPUT",message));
        adhocQueryviewRef.reset();
        JOptionPane.showMessageDialog(this,"Query Saved");
    }

    private void initToModal(DefaultListModel<String>model,String[] items)
    {
        model.clear();
        for(String item:items)
            model.addElement(item);
    }
    private void tableSelectorItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_tableSelectorItemStateChanged
        String tableName=(String)tableSelector.getSelectedItem();
        String[] cols=AdhocQuery.fetchColumnsByTableName(tableName);
        whereSelector.removeAllItems();
        for(String col : cols)
        {
            whereSelector.addItem(col);
        }
        initToModal(listModal,cols);
    }//GEN-LAST:event_tableSelectorItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> columnsSelector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label2;
    private javax.swing.JButton queryButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField sqlNameTextField;
    private javax.swing.JLabel tableLAbel;
    private javax.swing.JComboBox<String> tableSelector;
    private javax.swing.JTextField valueSelector;
    private javax.swing.JLabel where;
    private javax.swing.JLabel where1;
    private javax.swing.JComboBox<String> whereSelector;
    // End of variables declaration//GEN-END:variables
}
